import type { LucideIcon } from 'lucide-react';
import { Coffee, IceCream, CakeSlice, Flame } from 'lucide-react';

export type Recipe = {
  id: string;
  titulo: string;
  categoria:
    | 'cafe-da-manha-da-nutri'
    | 'sobremesas-zero'
    | 'bolos-para-comer-sem-culpa'
    | 'airfryer-proteica';
  ingredientes: string[];
  modo_preparo: string;
  imagem: string;
};

export type Category = {
  slug: Recipe['categoria'];
  title: string;
  description: string;
  Icon: LucideIcon;
  email: string;
  senha: string;
};

export const CATEGORIES: Category[] = [
  {
    slug: 'cafe-da-manha-da-nutri',
    title: 'Café da Manhã da Nutri',
    description: 'Comece o dia com energia e saúde. Receitas práticas para um café da manhã nutritivo.',
    Icon: Coffee,
    email: 'cafe@fit.com',
    senha: 'CAFEFIT1',
  },
  {
    slug: 'sobremesas-zero',
    title: 'Sobremesas Zero',
    description: 'Delícias sem açúcar para matar a vontade de doce sem sair da dieta.',
    Icon: IceCream,
    email: 'sobremesas@zero.com',
    senha: 'ZEROCAFE2',
  },
  {
    slug: 'bolos-para-comer-sem-culpa',
    title: 'Bolos para Comer Sem Culpa',
    description: 'Bolos fofinhos e saborosos em versões saudáveis para qualquer hora do dia.',
    Icon: CakeSlice,
    email: 'bolos@semculpa.com',
    senha: 'BOLOFIT3',
  },
  {
    slug: 'airfryer-proteica',
    title: 'Airfryer Proteica',
    description: 'Receitas ricas em proteína, feitas na airfryer para mais praticidade e menos gordura.',
    Icon: Flame,
    email: 'Airfryer@proteica.com',
    senha: 'PROTEINAFIT4',
  },
];

export const RECIPES: Recipe[] = [
  // Café da Manhã
  {
    id: 'crepioca-fit',
    titulo: 'Crepioca Fit',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-1',
    ingredientes: ['1 ovo', '2 colheres de sopa de goma de tapioca', '1 colher de sopa de requeijão light', 'Sal a gosto'],
    modo_preparo: 'Em uma tigela, bata o ovo com um garfo. Adicione a goma de tapioca, o requeijão light e uma pitada de sal, misturando bem até obter uma massa homogênea. Despeje a mistura em uma frigideira antiaderente pré-aquecida em fogo baixo. Deixe dourar de um lado e depois vire para dourar do outro. Sirva quente com o recheio de sua preferência.',
  },
  {
    id: 'panqueca-de-banana',
    titulo: 'Panqueca de Banana',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-1',
    ingredientes: ['1 banana prata madura amassada', '1 ovo', '2 colheres de sopa de aveia em flocos', 'Canela em pó a gosto'],
    modo_preparo: 'Em um prato fundo, amasse bem a banana. Adicione o ovo e a aveia, misturando tudo com um garfo até formar uma massa uniforme. Polvilhe canela a gosto. Aqueça uma frigideira antiaderente em fogo médio e despeje pequenas porções da massa. Cozinhe até as bordas firmarem e o centro borbulhar, depois vire e doure o outro lado. Sirva com mel ou frutas frescas.',
  },
  {
    id: 'suco-cascas-frutas',
    titulo: 'Suco de Cascas de Frutas',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-2',
    ingredientes: ['Cascas de 1 abacaxi e 1 manga', '1 litro de água filtrada', 'Adoçante ou açúcar a gosto'],
    modo_preparo: 'Higienize muito bem as cascas das frutas em água corrente. Em um liquidificador, coloque as cascas, adicione a água e bata em alta velocidade por cerca de 2 minutos. Coe a mistura com uma peneira fina ou um pano limpo para remover os resíduos sólidos. Adoce a gosto e sirva imediatamente com bastante gelo.',
  },
  {
    id: 'suco-laranja-funcho-hortela',
    titulo: 'Suco de Laranja com Funcho e Hortelã',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-3',
    ingredientes: ['2 laranjas descascadas e sem sementes', '1/2 talo de funcho fresco', '5 folhas de hortelã', '300ml de água gelada', 'Gelo a gosto'],
    modo_preparo: 'Pique as laranjas e o funcho em pedaços menores. Coloque todos os ingredientes no liquidificador e bata bem até a mistura ficar completamente homogênea. Se preferir um suco mais liso, coe antes de servir. Adicione mais gelo se desejar e sirva em seguida para aproveitar todos os nutrientes.',
  },
  {
    id: 'biscoito-de-cascas',
    titulo: 'Biscoito de Cascas e Talos de Vegetais',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-4',
    ingredientes: ['1 xícara de cascas e talos de vegetais (cenoura, abobrinha, brócolis) bem picados', '1 ovo', '2 colheres de sopa de manteiga amolecida', '1 colher de chá de fermento em pó', '1 e 1/2 xícara de farinha de trigo', '2 colheres de sopa de leite', 'Sal e temperos a gosto'],
    modo_preparo: 'Pré-aqueça o forno a 180°C. Em uma tigela, misture a farinha, o fermento e o sal. Adicione a manteiga e incorpore com a ponta dos dedos até formar uma farofa. Junte o ovo, o leite e os resíduos vegetais picados, misturando tudo até obter uma massa coesa. Abra a massa com um rolo, corte os biscoitos no formato desejado e asse em uma assadeira untada por cerca de 20 minutos ou até dourarem.',
  },
  {
    id: 'pao-de-tapioca',
    titulo: 'Pão de Tapioca',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-5',
    ingredientes: ['250g de tapioca granulada', '500ml de leite quente', '1 colher de chá de sal', '2 ovos', '50g de manteiga derretida', '100g de queijo parmesão ralado'],
    modo_preparo: 'Em uma tigela grande, misture a tapioca granulada com o leite quente e o sal. Deixe hidratar por cerca de 15 minutos, mexendo ocasionalmente, até a tapioca absorver o líquido. Em seguida, acrescente os ovos, a manteiga derretida e o queijo parmesão, misturando bem até a massa ficar homogênea. Com as mãos levemente untadas, modele pequenas bolinhas e distribua em uma assadeira antiaderente. Asse em forno pré-aquecido a 200°C por aproximadamente 25 minutos, ou até os pãezinhos crescerem e dourarem.',
  },
  {
    id: 'terere-tradicional',
    titulo: 'Tereré Tradicional',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-6',
    ingredientes: ['50g de erva-mate para tereré', '500ml de água bem gelada', 'Cubos de gelo a gosto', '1/2 limão espremido ou folhas de hortelã (opcional)'],
    modo_preparo: 'Em um copo apropriado (guampa), coloque a erva-mate até preencher cerca de 2/3 da capacidade. Incline o copo a 45 graus para que a erva se concentre em um lado e encaixe a bomba (bomba) no espaço vazio, firmando-a no fundo. Adicione cubos de gelo sobre a erva e complete lentamente com a água gelada. Se desejar, esprema um pouco de limão ou adicione folhas de hortelã para um toque extra de frescor.',
  },
  {
    id: 'bebida-quente-de-bocaiuva',
    titulo: 'Bebida Quente de Bocaiuva',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-7',
    ingredientes: ['2 colheres de sopa de farinha de bocaiuva', '200ml de leite (pode ser vegetal)', '1 pitada de canela em pó', 'Mel ou adoçante a gosto'],
    modo_preparo: 'Em uma panela pequena, com o fogo ainda desligado, dissolva completamente a farinha de bocaiuva no leite para não empelotar. Adicione a canela em pó. Leve ao fogo baixo, mexendo continuamente com um fouet, até a mistura aquecer bem e adquirir uma consistência levemente cremosa. Retire do fogo, adoce a gosto e sirva imediatamente.',
  },
  {
    id: 'quase-bolo-quase-pao-de-queijo',
    titulo: 'Quase Bolo, Quase Pão de Queijo',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-8',
    ingredientes: ['1 xícara de polvilho doce', '1/2 xícara de óleo de girassol', '2 ovos', '1/2 xícara de queijo ralado (parmesão ou meia cura)', '1 pitada de sal'],
    modo_preparo: 'Pré-aqueça o forno a 180°C. No liquidificador, adicione os ovos, o óleo, o queijo ralado, o sal e o polvilho doce. Bata tudo por cerca de 2 minutos, até obter uma massa completamente homogênea e lisa. Despeje a mistura em uma forma pequena (tipo bolo inglês) untada e enfarinhada. Asse por aproximadamente 25-30 minutos, ou até que cresça, fique firme e doure na superfície.',
  },
  {
    id: 'overnight-oats',
    titulo: 'Overnight Oats',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-9',
    ingredientes: ['4 colheres de sopa de aveia em flocos', '150ml de leite ou iogurte natural', '1 colher de sopa de sementes de chia', 'Frutas picadas a gosto (morango, banana, manga)', '1 colher de sopa de oleaginosas (castanhas, amêndoas)', 'Canela em pó a gosto', 'Mel ou xarope de bordo a gosto'],
    modo_preparo: 'Em um pote de vidro com tampa, comece com a camada de aveia e chia. Adicione o leite ou iogurte e mexa bem. Em seguida, intercale camadas de frutas picadas, oleaginosas e um toque de canela. Repita o processo até preencher o pote. Adoce se necessário. Feche bem e leve à geladeira por no mínimo 4 horas, ou idealmente, de um dia para o outro para que a aveia absorva o líquido e amacie.',
  },
  {
    id: 'pao-low-carb-de-microondas',
    titulo: 'Pão Low Carb de Micro-ondas',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-10',
    ingredientes: ['1 ovo', '2 colheres de sopa de farelo de aveia ou farinha de linhaça', '1 colher de sopa de requeijão ou iogurte', '1 colher de café de fermento em pó', '1 pitada de sal', 'Manteiga ou azeite para untar'],
    modo_preparo: 'Em uma tigela pequena ou caneca que possa ir ao micro-ondas, bata o ovo com um garfo. Adicione o farelo de aveia (ou linhaça), o requeijão, o sal e misture bem. Por último, incorpore o fermento delicadamente. Unte um pequeno recipiente, despeje a massa e leve ao micro-ondas em potência alta por cerca de 2 a 3 minutos, ou até a massa firmar. Desenforme e, se desejar, doure em uma frigideira com manteiga.',
  },
  {
    id: 'pao-de-frigideira-fit',
    titulo: 'Pão de Frigideira Fit',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-11',
    ingredientes: ['1 ovo', '1 colher de sopa de azeite', '2 colheres de sopa de água', '3 colheres de sopa de farelo de aveia', '1 colher de sopa de polvilho doce', 'Sal e orégano a gosto', '1 colher de café de fermento em pó'],
    modo_preparo: 'Em uma tigela, misture bem o ovo, o azeite e a água. Adicione o farelo de aveia, o polvilho, o sal, o orégano e, por último, o fermento, mexendo até a massa ficar homogênea. Aqueça uma frigideira antiaderente em fogo baixo, despeje a massa, tampe e cozinhe por cerca de 3-4 minutes. Quando a parte de cima estiver firme, vire e doure o outro lado por mais alguns minutos.',
  },
  {
    id: 'muffin-fit-de-banana',
    titulo: 'Muffin Fit de Banana',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-12',
    ingredientes: ['1 ovo', '2 colheres de sopa de farelo de aveia', '1 colher de sopa de farinha de coco', '1 banana madura amassada', 'Canela a gosto', '1 colher de sobremesa de cacau em pó (opcional)', '1/2 colher de café de fermento em pó'],
    modo_preparo: 'Em uma caneca ou recipiente de silicone que possa ir ao micro-ondas, amasse a banana e misture com o ovo. Adicione o farelo de aveia, a farinha de coco, a canela, o cacau (se usar) e mexa até formar uma massa homogênea. Incorpore o fermento por último. Leve ao micro-ondas por aproximadamente 2 minutos em potência alta. Verifique se está firme e cozido antes de retirar.',
  },
  {
    id: 'panqueca-low-carb-salgada',
    titulo: 'Panqueca Low Carb Salgada',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-13',
    ingredientes: ['2 ovos', '2 colheres de sopa de farinha de amêndoas', '1 colher de sopa de farelo de aveia', '1/2 colher de chá de fermento em pó', '1 colher de sopa de água', 'Sal e temperos a gosto (pimenta, orégano)'],
    modo_preparo: 'Em uma tigela, bata os ovos e adicione os demais ingredientes secos, misturando bem com um garfo ou fouet até a massa ficar uniforme. Aqueça uma frigideira antiaderente untada com um fio de azeite. Despeje pequenas porções da massa e cozinhe em fogo baixo, com a frigideira tampada, até firmar. Vire e doure do outro lado. Sirva com recheios salgados de sua preferência.',
  },
  {
    id: 'panqueca-doce-de-banana',
    titulo: 'Panqueca Doce de Banana',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-14',
    ingredientes: ['1 ovo', '3 colheres de sopa de farinha de amêndoas ou de arroz', '1 banana bem madura amassada', 'Canela em pó a gosto', 'Óleo de coco para untar'],
    modo_preparo: 'Em um prato, amasse bem a banana com um garfo e misture com o ovo e a canela. Adicione a farinha de sua escolha e mexa até incorporar completamente, formando uma massinha. Aqueça uma frigideira em fogo baixo, unte com óleo de coco e despeje pequenas porções da massa. Doure ambos os lados cuidadosamente e sirva com frutas ou mel.',
  },
  {
    id: 'pao-de-beijo-vegano',
    titulo: 'Pão de Beijo Vegano',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-15',
    ingredientes: ['1 xícara de polvilho doce', '1/2 xícara de polvilho azedo', '1/2 xícara de água morna', '1/4 xícara de azeite', '1 xícara de batata ou mandioquinha cozida e amassada', 'Sal e ervas finas a gosto'],
    modo_preparo: 'Pré-aqueça o forno a 200°C. Em uma tigela grande, misture os polvilhos. Adicione a água morna, o azeite, o legume amassado (que substitui o queijo), o sal e as ervas. Misture primeiro com uma colher e depois com as mãos até formar uma massa lisa que não grude. Modele pequenas bolinhas e distribua em uma assadeira antiaderente. Asse por cerca de 30 minutos ou até dourarem e ficarem crocantes por fora.',
  },
  {
    id: 'crepioca-de-chocolate',
    titulo: 'Crepioca de Chocolate',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-16',
    ingredientes: ['1 ovo', '1 clara', '2 colheres de sopa de goma de tapioca', 'Adoçante culinário a gosto', '1 colher de sopa de cacau em pó 100%'],
    modo_preparo: 'Em uma tigela, bata o ovo e a clara com um garfo. Adicione a goma de tapioca, o adoçante e o cacau em pó. Misture vigorosamente até que todos os ingredientes estejam bem incorporados e a massa fique lisa e sem grumos. Despeje a mistura em uma frigideira antiaderente pré-aquecida em fogo baixo e cozinhe até a massa firmar e as bordas se soltarem. Vire e doure levemente o outro lado. Recheie a gosto.',
  },
  {
    id: 'shake-hipercalorico',
    titulo: 'Shake Hipercalórico',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-17',
    ingredientes: ['1 scoop de whey protein (sabor de sua preferência)', '300ml de leite integral', '1 banana prata madura', '2 colheres de sopa de aveia em flocos', '5 cubos de gelo'],
    modo_preparo: 'Coloque todos os ingredientes no liquidificador: o leite, a banana picada, a aveia, o whey protein e o gelo. Bata em alta velocidade por cerca de 1 a 2 minutos, ou até a mistura ficar completamente homogênea e cremosa. Sirva imediatamente.',
  },
  {
    id: 'mingau-proteico-de-aveia',
    titulo: 'Mingau Proteico de Aveia',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-18',
    ingredientes: ['2 claras de ovo (ou 1 ovo inteiro)', '1 gema', '3 colheres de sopa de farinha de aveia', '150ml de água ou leite', 'Canela em pó a gosto'],
    modo_preparo: 'Em uma panela pequena, antes de levar ao fogo, misture bem as claras, a gema e a farinha de aveia até dissolver. Adicione a água (ou leite) e a canela. Leve ao fogo baixo, mexendo continuamente com um fouet para não empelotar. Continue mexendo até o mingau atingir a consistência desejada, mais grossa e cremosa.',
  },
  {
    id: 'barra-de-proteina-caseira',
    titulo: 'Barra de Proteína Caseira',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-19',
    ingredientes: ['1 xícara de aveia em flocos', '1/2 xícara de pasta de amendoim', '2 scoops de whey protein (sabor baunilha ou chocolate)', '2 colheres de sopa de sementes de linhaça', '3 a 4 colheres de sopa de água ou leite'],
    modo_preparo: 'Em uma tigela, misture a aveia, o whey protein e a linhaça. Adicione a pasta de amendoim e misture bem. Aos poucos, adicione a água ou leite, mexendo até formar uma massa densa e moldável. Forre uma forma pequena com plástico filme, espalhe a massa uniformemente e pressione bem. Leve ao congelador por 30 minutos para firmar. Retire, corte em barras e conserve na geladeira.',
  },
  {
    id: 'panqueca-low-carb-simples',
    titulo: 'Panqueca Low Carb Simples',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-13',
    ingredientes: ['2 ovos', '2 colheres de sopa de farinha de castanha ou chia', '1 colher de sopa de creme de leite', '1 colher de sopa de queijo parmesão ralado fino', 'Sal e pimenta a gosto'],
    modo_preparo: 'Em uma tigela, bata os ovos e adicione a farinha, o creme de leite e o queijo parmesão. Tempere com sal e pimenta e misture tudo muito bem com um garfo até a massa ficar homogênea. Aqueça uma frigideira antiaderente em fogo baixo, unte se necessário, e despeje metade da massa. Doure dos dois lados e repita o processo com o restante da massa.',
  },
  {
    id: 'pao-cetogenico-rapido',
    titulo: 'Pão Cetogênico Rápido',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-10',
    ingredientes: ['1 ovo grande', '2 colheres de sopa de farinha de coco', '1/2 colher de chá de fermento em pó', '1 pitada de sal'],
    modo_preparo: 'Em uma tigela pequena, bata o ovo com um garfo. Adicione a farinha de coco, o fermento e o sal, misturando rapidamente até incorporar. Despeje a massa em um pequeno recipiente quadrado ou redondo untado e leve ao micro-ondas por 90 segundos em potência alta. Desenforme, corte ao meio e doure as fatias em uma frigideira com manteiga para um acabamento crocante.',
  },
  {
    id: 'vitamina-de-banana-proteica',
    titulo: 'Vitamina de Banana Proteica',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-20',
    ingredientes: ['1 banana congelada em rodelas', '1/2 pote de iogurte natural desnatado', '1 scoop de whey protein de baunilha', '1 pitada de canela em pó', '1 colher de chá de café solúvel', '100ml de leite desnatado ou água'],
    modo_preparo: 'Coloque todos os ingredientes no liquidificador, começando pelos líquidos. Bata em alta velocidade até que a mistura esteja completamente lisa, cremosa e sem pedaços de banana. Se necessário, pare para raspar as laterais do copo. Sirva imediatamente para melhor consistência.',
  },
  {
    id: 'panqueca-para-hipertrofia',
    titulo: 'Panqueca para Hipertrofia',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-21',
    ingredientes: ['100ml de leite', '2 ovos', '4 colheres de sopa de aveia em flocos', '2 colheres de sopa de farinha integral', '1 fio de azeite', 'Recheio: 4 fatias de peito de peru e 2 colheres de sopa de queijo cottage'],
    modo_preparo: 'No liquidificador, bata o leite, os ovos, a aveia, a farinha integral e o azeite até obter uma massa lisa. Aqueça uma frigideira antiaderente e despeje porções da massa para formar as panquecas, dourando ambos os lados. Recheie cada disco de panqueca com peito de peru e queijo cottage, enrole e sirva.',
  },
  {
    id: 'barra-proteica-de-pasta-de-amendoim',
    titulo: 'Barra Proteica de Pasta de Amendoim',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-22',
    ingredientes: ['1/4 xícara de mel ou melado', '1/4 xícara de açúcar mascavo', '1 xícara de pasta de amendoim', '1 pitada de canela', '1/4 xícara de semente de linhaça', '2 xícaras de aveia em flocos'],
    modo_preparo: 'Em uma panela, aqueça o mel, o açúcar mascavo e a pasta de amendoim em fogo baixo, mexendo até ficar homogêneo. Retire do fogo e adicione a canela, a linhaça e a aveia, misturando bem. Pressione a mistura em uma forma forrada com papel manteiga e leve ao congelador por pelo menos 1 hora. Depois de firme, corte em barras.',
  },
  {
    id: 'panqueca-de-pasta-de-amendoim',
    titulo: 'Panqueca de Pasta de Amendoim',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-23',
    ingredientes: ['1/2 xícara de farinha de trigo', '1/4 xícara de farelo de trigo', '1 colher de sopa de açúcar mascavo', '1 ovo', '2 colheres de sopa de pasta de amendoim', '3/4 xícara de leite'],
    modo_preparo: 'Em uma tigela, misture a farinha, o farelo de trigo e o açúcar. Em outra tigela, bata o ovo e misture com a pasta de amendoim e o leite. Junte as duas misturas e mexa até ficar homogêneo. Aqueça uma frigideira untada e cozinhe pequenas porções da massa, dourando dos dois lados.',
  },
  {
    id: 'smoothie-de-pasta-de-amendoim',
    titulo: 'Smoothie de Pasta de Amendoim',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-24',
    ingredientes: ['1 scoop de whey protein de chocolate', '1 banana congelada', '2 colheres de sopa de pasta de amendoim', '200ml de leite', 'Gelo a gosto'],
    modo_preparo: 'Coloque todos os ingredientes no liquidificador. Bata em alta velocidade até a mistura ficar lisa, cremosa e atingir a consistência de um smoothie. Sirva imediatamente.',
  },
  {
    id: 'sanduiche-de-amendoim-com-geleia',
    titulo: 'Sanduíche de Amendoim com Geleia',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-25',
    ingredientes: ['2 colheres de sopa de pasta de amendoim integral', '1 colher de sopa de geleia sem açúcar (sabor de sua preferência)', '2 fatias de pão integral'],
    modo_preparo: 'Toste levemente as fatias de pão, se desejar. Em uma fatia, espalhe generosamente a pasta de amendoim. Na outra fatia, espalhe a geleia. Junte as duas fatias para montar o sanduíche e corte ao meio se preferir. É um lanche rápido, clássico e energético.',
  },
  {
    id: 'granola-caseira-amendoim',
    titulo: 'Granola Caseira de Amendoim',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-26',
    ingredientes: ['1/2 xícara de pasta de amendoim', '1/4 xícara de mel', '1 colher de chá de canela em pó', '1 colher de chá de extrato de baunilha', '2 xícaras de aveia em flocos grossos'],
    modo_preparo: 'Pré-aqueça o forno a 160°C. Em uma tigela, misture a pasta de amendoim, o mel, a canela e a baunilha. Adicione a aveia e incorpore bem. Espalhe a mistura em uma assadeira forrada com papel manteiga e asse por 20-25 minutos, mexendo na metade do tempo, até ficar dourada e crocante. Deixe esfriar completamente antes de guardar.',
  },
  {
    id: 'pasta-amendoim-caseira',
    titulo: 'Pasta de Amendoim Caseira',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-27',
    ingredientes: ['500g de amendoim torrado sem pele e sem sal'],
    modo_preparo: 'Se o amendoim estiver cru, asse em forno pré-aquecido a 180°C por cerca de 10-15 minutos, até dourar levemente. Deixe esfriar um pouco. Coloque o amendoim ainda morno em um processador de alimentos potente. Processe continuamente, parando para raspar as laterais do recipiente a cada minuto. O amendoim primeiro virará uma farofa, depois uma massa densa e, finalmente, uma pasta cremosa e lisa. Guarde em um pote de vidro bem fechado.',
  },
  {
    id: 'panqueca-proteica-de-ovo-aveia',
    titulo: 'Panqueca Proteica de Ovo e Aveia',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-28',
    ingredientes: ['4 claras de ovo', '4 colheres de sopa de aveia em flocos', '1 fio de azeite', 'Canela em pó a gosto'],
    modo_preparo: 'No liquidificador ou em uma tigela com um garfo, bata as claras de ovo com a aveia e a canela até obter uma mistura homogênea. Aqueça uma frigideira antiaderente com um fio de azeite. Despeje pequenas porções da massa e cozinhe em fogo baixo até firmar. Vire para dourar do outro lado. Sirva com frutas ou mel.',
  },
  {
    id: 'omelete-proteico',
    titulo: 'Omelete Proteico',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-29',
    ingredientes: ['3 claras de ovo', '1 ovo inteiro', '2 colheres de sopa de leite', '1/2 tomate picado sem sementes', '1 colher de sopa de cebolinha picada', '2 fatias de queijo branco picado', 'Sal e pimenta do reino a gosto', 'Azeite para untar'],
    modo_preparo: 'Em uma tigela, bata as claras e o ovo inteiro. Adicione o leite, o tomate, a cebolinha e o queijo, temperando com sal e pimenta. Misture bem. Aqueça uma frigideira antiaderente untada com azeite em fogo médio. Despeje a mistura de ovos e cozinhe, mexendo levemente no início. Quando as bordas estiverem firmes, dobre ao meio e cozinhe por mais um minuto de cada lado.',
  },
  {
    id: 'pao-de-mandioca-com-whey',
    titulo: 'Pão de Mandioca com Whey',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-30',
    ingredientes: ['500g de mandioca cozida e amassada', '2 ovos', '1 gema para pincelar', '10g de fermento biológico seco', '1 colher de sopa de manteiga', '1 pitada de sal', '1 colher de sopa de açúcar', '1/2 xícara de whey protein sem sabor'],
    modo_preparo: 'Em uma tigela, dissolva o fermento no açúcar. Adicione os ovos, a manteiga e a mandioca amassada, misturando bem. Aos poucos, incorpore o whey protein e o sal, sovando até obter uma massa macia e que não grude nas mãos. Deixe a massa descansar por 30 minutos. Modele os pães, pincele com a gema e asse em forno pré-aquecido a 180°C por cerca de 30 minutos, ou até dourar.',
  },
  {
    id: 'crepe-de-chocolate-com-whey',
    titulo: 'Crepe de Chocolate com Whey',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-31',
    ingredientes: ['1 colher de sopa de cacau em pó', '15g de chocolate amargo 70% derretido', '2 claras de ovo', 'Morangos picados para rechear', '1/2 scoop de whey protein de chocolate'],
    modo_preparo: 'Em uma tigela, bata as claras com um garfo. Adicione o cacau, o chocolate derretido e o whey protein, misturando bem até formar uma massa homogênea. Aqueça uma frigideira antiaderente em fogo baixo. Despeje a massa, formando um disco fino. Cozinhe por cerca de 1 minuto de cada lado. Retire, recheie com os morangos picados e dobre.',
  },
  {
    id: 'mini-panquecas-de-banana',
    titulo: 'Mini Panquecas de Banana',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-32',
    ingredientes: ['1 ovo', '2 colheres de sopa de farinha de aveia', '1/2 banana madura picada', 'Morangos fatiados para decorar', 'Mel para finalizar'],
    modo_preparo: 'Em uma tigela, misture o ovo com a farinha de aveia até obter uma massa lisa. Incorpore os pedacinhos de banana. Aqueça uma frigideira antiaderente em fogo médio e despeje pequenas colheradas da massa para formar as mini panquecas. Cozinhe até dourar de ambos os lados. Sirva com morangos frescos fatiados e um fio de mel por cima.',
  },
  {
    id: 'pao-de-queijo-de-frigideira',
    titulo: 'Pão de Queijo de Frigideira',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-33',
    ingredientes: ['1 ovo', '2 colheres de sopa de goma de tapioca', '1 fatia de muçarela light', '1 colher de sopa de queijo parmesão ralado', '1 pitada de sal'],
    modo_preparo: 'Em uma tigela, bata o ovo e adicione a goma de tapioca, metade do parmesão e o sal, misturando bem. Despeje na frigideira antiaderente em fogo baixo. Quando a massa firmar, coloque a muçarela e o restante do parmesão em uma metade e dobre a outra por cima. Pressione levemente e doure dos dois lados.',
  },
  {
    id: 'vitamina-hiperproteica',
    titulo: 'Vitamina Hiperproteica',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-34',
    ingredientes: ['200ml de leite desnatado', '1 scoop de whey protein ou albumina (sabor de sua preferência)', '1 xícara de morangos congelados'],
    modo_preparo: 'Coloque todos os ingredientes no liquidificador. Bata em alta velocidade por cerca de 1 a 2 minutos, até a mistura ficar completamente homogênea, cremosa e sem pedaços de fruta. Sirva imediatamente para uma consistência perfeita.',
  },
  {
    id: 'requeijao-caseiro',
    titulo: 'Requeijão Caseiro',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-35',
    ingredientes: ['1 litro de leite integral', '4 colheres de sopa de suco de limão ou vinagre branco', '1 colher de sopa de manteiga sem sal', 'Sal a gosto'],
    modo_preparo: 'Aqueça o leite em uma panela até começar a ferver. Desligue o fogo, adicione o suco de limão e mexa delicadamente. Deixe descansar por 5 minutos para talhar. Coe a mistura em uma peneira fina forrada com um pano limpo para separar a massa do soro. Transfira a massa para um liquidificador, adicione a manteiga, o sal e um pouco do soro (2 a 3 colheres de sopa). Bata até ficar cremoso e liso. Leve à geladeira por pelo menos 2 horas para firmar.',
  },
  {
    id: 'manteiga-de-azeite',
    titulo: 'Manteiga de Azeite',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-36',
    ingredientes: ['250ml de azeite extra virgem de boa qualidade', 'Ervas frescas a gosto (alecrim, tomilho)', 'Grãos de pimenta a gosto', '1 dente de alho (opcional)'],
    modo_preparo: 'No liquidificador, bata o azeite com as ervas, os grãos de pimenta e o alho, se estiver usando, até que tudo esteja bem incorporado. Despeje a mistura em um recipiente que possa ir ao freezer e congele por algumas horas, até solidificar. Depois de firme, transfira para a geladeira. A textura ficará cremosa como a de uma manteiga para passar no pão.',
  },
  {
    id: 'panini-proteico',
    titulo: 'Panini Proteico',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-37',
    ingredientes: ['1 ovo', '2 colheres de sopa de queijo cottage', '2 colheres de sopa de farinha de aveia ou linhaça', '1/2 colher de chá de fermento em pó', 'Sal e temperos a gosto'],
    modo_preparo: 'Em uma tigela, misture bem o ovo, o cottage e a farinha. Adicione o fermento, sal e temperos, incorporando tudo. Despeje em uma forma pequena untada e leve ao micro-ondas por 3 minutos. Depois de firme, corte ao meio e doure as fatias em uma sanduicheira ou frigideira até ficar crocante.',
  },
  {
    id: 'smoothie-de-banana-com-morango',
    titulo: 'Smoothie de Banana com Morango',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-38',
    ingredientes: ['200ml de leite', '1 banana madura', '1 xícara de morangos', '1/2 pote de iogurte natural', 'Gotas de essência de baunilha', 'Mel a gosto'],
    modo_preparo: 'Bata todos os ingredientes no liquidificador até obter uma mistura cremosa e homogênea. Sirva imediatamente, bem gelado.',
  },
  {
    id: 'aipim-com-ghee',
    titulo: 'Aipim com Ghee',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-39',
    ingredientes: ['500g de aipim (mandioca)', '2 colheres de sopa de manteiga ou ghee', 'Sal a gosto'],
    modo_preparo: 'Descasque e corte o aipim em pedaços. Cozinhe em água e sal até ficar bem macio. Escorra a água e sirva quente, finalizando com a manteiga ghee por cima para derreter.',
  },
  {
    id: 'muesli-proteico',
    titulo: 'Muesli Proteico',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-40',
    ingredientes: ['1 pote de iogurte natural', '1/4 xícara de leite', '4 colheres de sopa de aveia', '1 colher de sopa de linhaça', '1 colher de chá de mel', '1/2 maçã picada', 'Nozes e uvas-passas a gosto'],
    modo_preparo: 'Em uma tigela, misture o iogurte, o leite, a aveia, a linhaça e o mel. Deixe descansar na geladeira por pelo menos 1 hora. Na hora de servir, adicione a maçã picada, as nozes e as uvas-passas.',
  },
  {
    id: 'tapioca-proteica',
    titulo: 'Tapioca Proteica',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-41',
    ingredientes: ['4 colheres de sopa de goma de tapioca', '1 colher de sopa de sementes de chia', '1 ovo cozido e amassado', 'Sal a gosto'],
    modo_preparo: 'Peneire a goma de tapioca com a chia sobre uma frigideira antiaderente aquecida. Quando formar uma massa única, espalhe o ovo cozido amassado por cima, tempere com sal, dobre ao meio e sirva.',
  },
  {
    id: 'cafe-batido-com-oleo-de-coco',
    titulo: 'Café Batido com Óleo de Coco',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-42',
    ingredientes: ['1 xícara de café quente', '1 colher de sopa de óleo de coco'],
    modo_preparo: 'No liquidificador ou com um mixer de mão, bata o café quente com o óleo de coco até formar uma espuma cremosa na superfície. Sirva imediatamente.',
  },
  {
    id: 'granola-caseira-2',
    titulo: 'Granola Caseira',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-43',
    ingredientes: ['2 xícaras de aveia em flocos grossos', '1/2 xícara de flocos de milho sem açúcar', '1/4 xícara de linhaça', '1/4 xícara de farelo de amaranto', '2 colheres de sopa de óleo de coco', '3 colheres de sopa de mel', '1 colher de sopa de cacau em pó', 'Canela a gosto', '1 xícara de mix de castanhas', '1/2 xícara de frutas secas'],
    modo_preparo: 'Pré-aqueça o forno a 160°C. Misture todos os ingredientes, exceto as frutas secas, e espalhe em uma assadeira. Asse por 30 minutos, mexendo na metade do tempo. Depois de frio, adicione as frutas secas e guarde em um pote bem fechado.',
  },
  {
    id: 'cambuquira-com-ovos',
    titulo: 'Cambuquira com Ovos',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-44',
    ingredientes: ['1 maço de cambuquira (brotos de abóbora)', '3 ovos', '1 cebola pequena picada', '2 dentes de alho picados', 'Azeite para refogar', 'Sal e pimenta a gosto'],
    modo_preparo: 'Refogue a cebola e o alho no azeite. Adicione a cambuquira lavada e picada e refogue até murchar. Abra um espaço no meio da panela, quebre os ovos e mexa delicadamente até cozinharem. Tempere com sal e pimenta.',
  },
  {
    id: 'pao-integral',
    titulo: 'Pão Integral',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-45',
    ingredientes: ['2 ovos', '1/2 xícara de óleo', '1 colher de sopa de manteiga', '1 xícara de leite morno', '1 xícara de água morna', '1 colher de sopa de sal', '2 sachês de fermento biológico seco', '1/2 xícara de aveia', '1/2 xícara de linhaça', 'Aproximadamente 1kg de farinha integral'],
    modo_preparo: 'No liquidificador, bata os ovos, óleo, manteiga, leite, água e sal. Em uma tigela, misture o fermento, aveia, linhaça e metade da farinha. Despeje o líquido e vá adicionando mais farinha até a massa soltar das mãos. Sove, deixe crescer e asse em forno a 180°C até dourar.',
  },
  {
    id: 'pao-de-cenoura',
    titulo: 'Pão de Cenoura',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-46',
    ingredientes: ['2 cenouras médias cozidas', '2 ovos', '1/2 xícara de óleo', '1 xícara de leite morno', '2 colheres de sopa de açúcar', '1 colher de chá de sal', '2 sachês de fermento biológico seco', 'Aproximadamente 1kg de farinha de trigo'],
    modo_preparo: 'Bata a cenoura com os líquidos, ovos, açúcar e sal no liquidificador. Misture com o fermento e a farinha até dar ponto. Deixe a massa crescer, modele os pães e asse em forno médio até dourar.',
  },
  {
    id: 'bolinho-de-chuva',
    titulo: 'Bolinho de Chuva',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-47',
    ingredientes: ['2 ovos', '1 xícara de açúcar', '2 e 1/2 xícaras de farinha de trigo', '1 xícara de leite', '1 colher de sopa de fermento em pó'],
    modo_preparo: 'Misture todos os ingredientes até obter uma massa cremosa. Com uma colher, pegue porções da massa e frite em óleo quente ou asse na airfryer a 180°C até dourar. Passe no açúcar com canela.',
  },
  {
    id: 'crepioca-2',
    titulo: 'Crepioca',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-1',
    ingredientes: ['2 colheres de sopa de goma de tapioca', '1 ovo'],
    modo_preparo: 'Em uma tigela, misture a goma de tapioca e o ovo até ficar homogêneo. Despeje em uma frigideira antiaderente aquecida e cozinhe dos dois lados até dourar.',
  },
  {
    id: 'pao-com-ora-pro-nobis',
    titulo: 'Pão com Ora-pro-nóbis',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-48',
    ingredientes: ['1kg de farinha de trigo', '2 ovos', '2 colheres de sopa de açúcar', '10g de fermento biológico seco', '1 colher de sopa de sal', '1/2 xícara de leite', '1 xícara de água', '1/2 xícara de óleo', '2 xícaras de folhas de ora-pro-nóbis'],
    modo_preparo: 'Bata os líquidos com as folhas de ora-pro-nóbis no liquidificador. Em uma tigela, misture a farinha, açúcar, sal e fermento. Adicione o líquido e sove até a massa ficar lisa. Deixe crescer, modele e asse até dourar.',
  },
  {
    id: 'barrinha-de-cereal-com-castanhas',
    titulo: 'Barrinha de Cereal com Castanhas',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-49',
    ingredientes: ['1 xícara de aveia', '1/2 xícara de gergelim', '1/2 xícara de açúcar mascavo', '1/4 xícara de melado', '1/2 xícara de amêndoas', '1/2 xícara de castanhas', '1 banana amassada', 'Canela a gosto', '1 colher de sopa de óleo de coco'],
    modo_preparo: 'Misture todos os ingredientes e espalhe em uma forma untada. Asse em forno a 180°C por 20 minutos ou até firmar. Deixe esfriar e corte em barras.',
  },
  {
    id: 'barrinha-de-cereal-com-amendoim',
    titulo: 'Barrinha de Cereal com Amendoim',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-50',
    ingredientes: ['1/2 xícara de linhaça', '1 xícara de aveia', '1 xícara de açúcar', '1 xícara de amendoim torrado', '1/2 xícara de leite', '1 colher de chá de fermento', 'Uvas-passas a gosto'],
    modo_preparo: 'Misture todos os ingredientes e modele em formato de barras. Asse em forno médio pré-aquecido até dourar. Deixe esfriar para firmar.',
  },
  {
    id: 'bolinho-salgado-de-milho',
    titulo: 'Bolinho Salgado de Milho',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-51',
    ingredientes: ['1 lata de milho verde', '2 ovos', '1/2 xícara de queijo ralado', '1 xícara de leite', '2 colheres de sopa de manteiga', '1 xícara de fubá', '1 colher de sopa de fermento', '1 abobrinha ralada', '1 cebola picada', '2 dentes de alho', 'Sal e pimenta a gosto'],
    modo_preparo: 'Bata o milho com os líquidos no liquidificador. Refogue os temperos e a abobrinha. Misture tudo com os ingredientes secos. Coloque em forminhas e asse em forno a 180°C até firmar.',
  },
  {
    id: 'crepioca-simples',
    titulo: 'Crepioca Simples',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-1',
    ingredientes: ['2 ovos', '2 colheres de sopa de goma de tapioca', '2 colheres de sopa de água'],
    modo_preparo: 'Bata todos os ingredientes com um garfo. Despeje em uma frigideira antiaderente aquecida e cozinhe dos dois lados.',
  },
  {
    id: 'mingau-com-pasta-de-amendoim',
    titulo: 'Mingau com Pasta de Amendoim',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-52',
    ingredientes: ['3 colheres de sopa de farelo de aveia', '2 claras de ovo', '1 colher de sopa de pasta de amendoim', 'Canela e cacau a gosto'],
    modo_preparo: 'Cozinhe a aveia com água até virar um mingau. Desligue o fogo e adicione as claras, mexendo vigorosamente. Finalize com a pasta de amendoim, canela e cacau.',
  },
  {
    id: 'mingau-proteico-com-banana',
    titulo: 'Mingau Proteico com Banana',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-53',
    ingredientes: ['1 scoop de proteína em pó', '3 colheres de sopa de aveia', '1/2 banana amassada', 'Cacau e canela a gosto'],
    modo_preparo: 'Misture todos os ingredientes em uma panela com um pouco de água. Leve ao fogo baixo, mexendo até encorpar. Pode ser feito no micro-ondas também.',
  },
  {
    id: 'panqueca-de-tapioca',
    titulo: 'Panqueca de Tapioca',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-1',
    ingredientes: ['1 ovo', '2 colheres de sopa de goma de tapioca', '1/2 banana amassada', 'Canela a gosto'],
    modo_preparo: 'Misture todos os ingredientes com um garfo. Asse em frigideira antiaderente dos dois lados, em fogo baixo.',
  },
  {
    id: 'panqueca-fit-de-banana-2',
    titulo: 'Panqueca Fit de Banana',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-14',
    ingredientes: ['1 banana prata madura', '1 ovo', '1 colher de sopa de aveia', 'Canela a gosto'],
    modo_preparo: 'Amasse a banana, misture com o ovo, a aveia e a canela. Asse em frigideira antiaderente em fogo baixo dos dois lados.',
  },
  {
    id: 'panqueca-rica-em-fibras',
    titulo: 'Panqueca Rica em Fibras',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-54',
    ingredientes: ['1 banana', '1 ovo', '2 colheres de sopa de aveia'],
    modo_preparo: 'Em um prato, amasse bem a banana com um garfo. Adicione o ovo e a aveia, misturando tudo até formar uma massa homogênea. Aqueça uma frigideira antiaderente em fogo baixo e despeje a massa, formando um disco. Cozinhe até dourar de um lado, depois vire e doure do outro.',
  },
  {
    id: 'pao-de-queijo-caseiro',
    titulo: 'Pão de Queijo Caseiro',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-8',
    ingredientes: ['250g de polvilho azedo', '250g de polvilho doce', '200g de queijo ralado', '3 ovos', '1 xícara de água fervente', '1/2 xícara de óleo', '1 colher de chá de sal'],
    modo_preparo: 'Em uma tigela, misture os polvilhos. Ferva a água com o óleo e o sal e escalde a mistura de polvilhos, mexendo bem. Deixe esfriar um pouco e adicione os ovos e o queijo, sovando até a massa ficar lisa. Modele bolinhas e asse em forno pré-aquecido a 180°C até dourar.',
  },
  {
    id: 'pao-de-queijo-sem-lactose',
    titulo: 'Pão de Queijo sem Lactose',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-55',
    ingredientes: ['500g de inhame cozido e amassado', '1/4 xícara de azeite', '1 colher de chá de sal', '500g de polvilho doce'],
    modo_preparo: 'Em uma tigela, misture o inhame amassado com o azeite e o sal. Aos poucos, adicione o polvilho doce, sovando até a massa ficar homogênea e soltar das mãos. Se necessário, ajuste a quantidade de polvilho. Modele pequenas bolinhas, distribua em uma assadeira e asse em forno pré-aquecido a 200°C por cerca de 30 minutos ou até dourarem.',
  },
  {
    id: 'pao-de-aveia-no-microondas',
    titulo: 'Pão de Aveia no Micro-ondas',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-10',
    ingredientes: ['2 ovos', '2 colheres de sopa de água', '4 colheres de sopa de farinha de aveia', '1 colher de chá de fermento em pó', 'Orégano e pimenta a gosto'],
    modo_preparo: 'Em uma tigela que possa ir ao micro-ondas, bata os ovos com a água. Adicione a farinha de aveia, o orégano e a pimenta, misturando bem. Por último, incorpore o fermento. Leve ao micro-ondas por cerca de 3 minutos em potência alta, ou até a massa firmar. Desenforme e, se desejar, doure as fatias em uma frigideira.',
  },
  {
    id: 'pao-de-queijo-low-carb',
    titulo: 'Pão de Queijo Low Carb',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-56',
    ingredientes: ['2 ovos', '1 xícara de queijo sem lactose ralado', '1/2 xícara de sementes de girassol trituradas', '1/4 xícara de farinha de coco', '2 colheres de sopa de psyllium', '1 colher de sopa de chia', 'Sal a gosto', '1 colher de sopa de fermento em pó', '1/2 colher de chá de goma xantana'],
    modo_preparo: 'Em uma tigela, misture todos os ingredientes secos. Adicione os ovos e o queijo, mexendo bem até formar uma massa homogênea. Deixe a massa descansar por 10 minutos para hidratar. Modele pãezinhos, coloque em uma assadeira e asse em forno pré-aquecido a 180°C por 20-25 minutos, ou até dourarem.',
  },
  {
    id: 'pao-de-queijo-rapido',
    titulo: 'Pão de Queijo Rápido',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-8',
    ingredientes: ['2 xícaras de polvilho doce', '1 xícara de queijo parmesão ralado', '1 caixinha de creme de leite (200g)', '1 pitada de sal'],
    modo_preparo: 'Em uma tigela, misture o polvilho, o queijo e o sal. Adicione o creme de leite aos poucos, mexendo com as mãos até formar uma massa que desgrude. Se a massa ficar muito seca, adicione mais creme de leite; se ficar grudenta, adicione mais polvilho. Modele bolinhas e asse em forno pré-aquecido a 200°C por cerca de 20 minutos, ou até dourarem.',
  },
  {
    id: 'pao-integral-de-liquidificador',
    titulo: 'Pão Integral de Liquidificador',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-45',
    ingredientes: ['1 xícara de polvilho doce', '1 xícara de farinha de arroz', '1/2 xícara de farelo de aveia', '1/4 xícara de azeite ou óleo de coco', '2 ovos', '1 xícara de água morna', '1 colher de sopa de fermento biológico seco', '1 colher de chá de sal', 'Sementes a gosto para decorar'],
    modo_preparo: 'No liquidificador, bata os ovos, a água e o azeite. Em uma tigela, misture as farinhas, o sal e as sementes. Despeje a mistura líquida sobre os secos e mexa bem. Adicione o fermento e incorpore delicadamente. Despeje a massa em uma forma de pão untada e deixe crescer por 30 minutos. Asse em forno pré-aquecido a 180°C por cerca de 30-40 minutos, ou até o palito sair limpo.',
  },
  {
    id: 'pate-de-frango-saudavel',
    titulo: 'Patê de Frango Saudável',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-57',
    ingredientes: ['200g de frango cozido e desfiado', '1 pote de iogurte natural desnatado', '1 colher de chá de açafrão', 'Orégano a gosto', 'Suco de 1/2 limão', '1 fio de azeite', '1/2 cenoura ralada', '1/4 de pimentão picado', 'Azeitonas picadas a gosto', 'Sal e cebolinha a gosto'],
    modo_preparo: 'Em uma tigela, misture o iogurte com o açafrão, orégano, suco de limão, azeite e sal. Adicione o frango desfiado, a cenoura, o pimentão e as azeitonas, incorporando tudo. Finalize com a cebolinha picada. Leve à geladeira por pelo menos 30 minutos antes de servir para apurar os sabores.',
  },
  {
    id: 'panqueca-de-aveia',
    titulo: 'Panqueca de Aveia',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-1',
    ingredientes: ['1 xícara de aveia em flocos finos', '1 xícara de água', '1 colher de sopa de melado de cana', '1 colher de sopa de farinha de linhaça', '1/2 colher de chá de fermento em pó'],
    modo_preparo: 'No liquidificador, bata a aveia, a água, o melado e a farinha de linhaça até obter uma massa lisa. Deixe descansar por 5 minutos. Incorpore o fermento delicadamente. Aqueça uma frigideira antiaderente em fogo baixo e despeje pequenas porções da massa, dourando dos dois lados.',
  },
  {
    id: 'granola-caseira-3',
    titulo: 'Granola Caseira',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-43',
    ingredientes: ['2 xícaras de aveia em flocos grossos', '1 xícara de mix de oleaginosas (castanhas, amêndoas, nozes)', '2 colheres de sopa de óleo de coco', '3 colheres de sopa de mel', '1 colher de sopa de chia', '1 colher de sopa de linhaça', 'Canela em pó a gosto', '1/2 xícara de uvas-passas', '1 pitada de sal'],
    modo_preparo: 'Pré-aqueça o forno a 160°C. Em uma tigela grande, misture a aveia, as oleaginosas, o óleo de coco, o mel, a chia, a linhaça, a canela e o sal. Espalhe a mistura em uma assadeira forrada e asse por 25-30 minutos, mexendo na metade do tempo para dourar por igual. Retire do forno, espere esfriar e adicione as uvas-passas. Guarde em um pote bem fechado.',
  },
  {
    id: 'pao-de-abobora',
    titulo: 'Pão de Abóbora',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-58',
    ingredientes: ['1 xícara de abóbora cabotiá cozida e amassada', '1/2 xícara de polvilho doce', '1/2 xícara de polvilho azedo', '1/4 xícara de água', '2 colheres de sopa de óleo de coco', '1 colher de sopa de chia', 'Sal a gosto'],
    modo_preparo: 'Pré-aqueça o forno a 200°C. Em uma tigela, misture a abóbora amassada com os polvilhos, a água, o óleo de coco, a chia e o sal. Mexa bem até formar uma massa homogênea e que seja possível modelar. Faça pequenas bolinhas e coloque em uma assadeira antiaderente. Asse por cerca de 25-30 minutos ou até que os pãezinhos estejam dourados.',
  },
  {
    id: 'pao-integral-microondas',
    titulo: 'Pão Integral de Micro-ondas',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-59',
    ingredientes: ['1 ovo', '2 colheres de sopa de farelo de aveia', '1 colher de sopa de iogurte natural ou água', '1/2 colher de chá de fermento em pó', 'Ervas ou sementes a gosto'],
    modo_preparo: 'Em uma caneca ou tigela, misture bem o ovo, o farelo de aveia e o iogurte. Adicione o fermento e as ervas, mexendo delicadamente. Leve ao micro-ondas por cerca de 2-3 minutos em potência alta. Desenforme e, se desejar, doure em uma frigideira ou sanduicheira.',
  },
  {
    id: 'crepe-whey-protein',
    titulo: 'Crepe de Whey Protein',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-60',
    ingredientes: ['1 scoop de whey protein (sabor de sua preferência)', '2 claras de ovo'],
    modo_preparo: 'Em uma tigela, bata as claras levemente com um garfo. Adicione o whey protein e misture bem até dissolver completamente e formar uma massa homogênea. Aqueça uma frigideira antiaderente em fogo baixo e despeje a massa, formando um disco fino. Cozinhe por cerca de 1 minuto de cada lado, até firmar. Sirva com frutas ou a cobertura de sua preferência.',
  },
  {
    id: 'pao-sem-gluten-lactose',
    titulo: 'Pão sem Glúten e sem Lactose',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-61',
    ingredientes: ['3 ovos', '1/2 xícara de leite de coco', '1/2 xícara de água morna', '1/4 xícara de azeite', '1 e 1/2 xícara de farinha de arroz', '1/2 xícara de polvilho doce', '1/2 xícara de fubá', '2 colheres de sopa de açúcar demerara', '1 colher de chá de sal', '10g de fermento biológico seco'],
    modo_preparo: 'No liquidificador, bata os ovos, o leite de coco, a água e o azeite. Em uma tigela, misture as farinhas, o fubá, o açúcar e o sal. Despeje a mistura líquida sobre os secos e mexa bem. Adicione o fermento e incorpore. Despeje em uma forma de pão untada, deixe crescer por 30 minutos e asse em forno a 180°C por 35-40 minutos.',
  },
  {
    id: 'omelete-proteica-completa',
    titulo: 'Omelete Proteica',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-62',
    ingredientes: ['3 claras', '1 gema', '1/2 tomate picado', '1/4 cebola picada', 'Salsa a gosto', '2 colheres de frango desfiado', '1 colher de ervilha', '1 fio de manteiga', '1 fatia de queijo branco', '1/2 scoop de whey', '1 colher de farinha de aveia', 'Sal e orégano a gosto'],
    modo_preparo: 'Em uma tigela, misture todos os ingredientes até obter uma massa homogênea. Aqueça uma frigideira antiaderente com um fio de manteiga ou azeite e despeje a mistura. Cozinhe em fogo baixo, com a frigideira tampada, até a parte de cima firmar. Dobre ao meio e sirva.',
  },
  {
    id: 'crepioca-temperada',
    titulo: 'Crepioca Temperada',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-63',
    ingredientes: ['1 ovo', '2 colheres de sopa de goma de tapioca', '1 colher de sopa de queijo parmesão ralado', 'Salsinha picada a gosto', 'Sal e temperos a gosto'],
    modo_preparo: 'Bata o ovo com um garfo e misture a goma de tapioca, o queijo parmesão, a salsinha e os temperos. Aqueça uma frigideira antiaderente em fogo baixo e despeje a massa, espalhando para formar uma panqueca fina. Cozinhe até dourar dos dois lados.',
  },
  {
    id: 'muffin-de-pitanga',
    titulo: 'Muffin de Pitanga',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-64',
    ingredientes: ['1 xícara de farinha sem glúten', '1/2 xícara de açúcar demerara', '1 xícara de pitangas frescas sem caroço', '1/4 xícara de óleo de coco', '1/4 xícara de água', '1 colher de chá de extrato de baunilha', '1 colher de sopa de farinha de linhaça', '1 colher de chá de fermento em pó'],
    modo_preparo: 'Pré-aqueça o forno a 180°C. Em uma tigela, misture a farinha, o açúcar, a linhaça e o fermento. Em outra, misture o óleo, a água e a baunilha. Junte as duas misturas e incorpore as pitangas. Distribua em forminhas de muffin e asse por 20-25 minutos.',
  },
  {
    id: 'bolo-amendoas-cacau',
    titulo: 'Bolo de Amêndoas e Cacau',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-65',
    ingredientes: ['1 ovo', '2 colheres de sopa de farinha de aveia', '2 colheres de sopa de farinha de amêndoas', '1 colher de sopa de óleo de coco', '1 colher de sopa de cacau em pó', 'Mel ou adoçante a gosto', '1/2 colher de chá de fermento em pó'],
    modo_preparo: 'Em uma caneca grande, misture todos os ingredientes com um garfo até obter uma massa homogênea. Leve ao micro-ondas em potência alta por cerca de 2 a 3 minutos, ou até que o bolo esteja firme ao toque. Sirva na própria caneca.',
  },
  {
    id: 'banana-pao-assada',
    titulo: 'Banana-pão Assada',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-66',
    ingredientes: ['1 banana-pão madura', '2 claras de ovo', 'Gotas de essência de baunilha', 'Um pouco de água', 'Canela em pó a gosto'],
    modo_preparo: 'Asse a banana-pão com casca em forno a 180°C até ficar macia. Retire a polpa, amasse bem e misture com as claras, a baunilha e a canela. Leve a uma panela com um pouco de água e cozinhe em fogo baixo, mexendo, até engrossar e virar um creme.',
  },
  {
    id: 'tapioca-fitness',
    titulo: 'Tapioca Fitness',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-67',
    ingredientes: ['Goma de tapioca', 'Queijo minas ou ricota', 'Frango desfiado', 'Frutas picadas', 'Chocolate amargo 70%'],
    modo_preparo: 'Peneire a goma de tapioca sobre uma frigideira antiaderente aquecida, formando um disco. Quando a massa se unir, adicione o recheio de sua preferência: para uma versão salgada, use queijo e frango; para uma doce, use frutas e pedaços de chocolate. Dobre e sirva.',
  },
  {
    id: 'suco-detoxificante',
    titulo: 'Suco Detoxificante',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-68',
    ingredientes: ['200ml de água', '1 folha de couve', 'Algumas folhas de hortelã', '1/2 maçã', '1/2 pepino', '1 rodela fina de gengibre'],
    modo_preparo: 'Lave bem todos os ingredientes. Pique a maçã e o pepino. Coloque tudo no liquidificador e bata em alta velocidade até a mistura ficar completamente líquida e homogênea. Sirva imediatamente, sem coar, para aproveitar todas as fibras.',
  },
  {
    id: 'suco-gaseificado',
    titulo: 'Suco Gaseificado',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-69',
    ingredientes: ['200ml de água com gás gelada', '2 fatias de abacaxi', 'Folhas de hortelã a gosto', 'Gelo', 'Suco de 1/2 limão'],
    modo_preparo: 'No liquidificador, bata o abacaxi, a hortelã, o suco de limão e o gelo (sem a água com gás). Despeje a mistura em um copo e complete suavemente com a água com gás para não perder o efeito efervescente. Sirva em seguida.',
  },
  {
    id: 'suco-rosa',
    titulo: 'Suco Rosa',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-70',
    ingredientes: ['200ml de água', '1 fatia de melancia', '1/4 de beterraba crua', '1 rodela fina de gengibre', '1 pitada de canela em pó'],
    modo_preparo: 'Pique a melancia e a beterraba. Coloque todos os ingredientes no liquidificador e bata bem até obter uma mistura lisa e vibrante. Sirva gelado.',
  },
  {
    id: 'suco-verde',
    titulo: 'Suco Verde',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-71',
    ingredientes: ['200ml de água de coco', '1 folha de couve', '1/2 maçã', 'Suco de 1/2 limão', '1 rodela de gengibre'],
    modo_preparo: 'Lave bem a couve e a maçã. Coloque todos os ingredientes no liquidificador e bata em alta potência até que a mistura esteja completamente homogênea. Sirva imediatamente, sem coar, para um máximo aproveitamento dos nutrientes.',
  },
  {
    id: 'sucha-hibisco-morango',
    titulo: 'Suchá de Hibisco com Morango',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-72',
    ingredientes: ['200ml de chá de hibisco gelado', '5 morangos frescos ou congelados', 'Folhas de hortelã a gosto', 'Gelo'],
    modo_preparo: 'Prepare o chá de hibisco e deixe esfriar completamente. No liquidificador, bata o chá gelado, os morangos, a hortelã e o gelo até obter uma bebida refrescante e homogênea. Sirva em seguida.',
  },
  {
    id: 'pao-de-queijo-low-carb-2',
    titulo: 'Pão de Queijo Low Carb',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-56',
    ingredientes: ['2 ovos', '1 colher de sopa de manteiga derretida', '1 xícara de queijo parmesão ralado', '1/2 xícara de queijo muçarela ralado', '1 colher de chá de fermento em pó', '3 colheres de sopa de farinha de linhaça ou amêndoas'],
    modo_preparo: 'Pré-aqueça o forno a 180°C. Em uma tigela, misture os ovos, a manteiga e os queijos. Adicione a farinha e o fermento, mexendo bem. Distribua a massa em forminhas de silicone ou de empada e asse por cerca de 20 minutos, ou até dourarem.',
  },
  {
    id: 'pao-rapidex',
    titulo: 'Pão Rapidex',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-73',
    ingredientes: ['1 ovo', '2 colheres de sopa de farinha de aveia', '1 colher de sopa de farinha de amêndoas', 'Sal e especiarias a gosto'],
    modo_preparo: 'Em uma tigela pequena, misture bem todos os ingredientes com um garfo até formar uma massa lisa. Aqueça uma frigideira pequena antiaderente em fogo baixo e despeje a massa. Cozinhe por cerca de 2-3 minutos de cada lado, até firmar e dourar.',
  },
  {
    id: 'pate-de-atum',
    titulo: 'Patê de Atum',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-74',
    ingredientes: ['1 lata de atum sólido ao natural, escorrido', '2 colheres de sopa de azeite', 'Salsinha picada a gosto', 'Orégano a gosto', 'Azeitonas verdes picadas a gosto'],
    modo_preparo: 'Em uma tigela, amasse o atum com um garfo. Adicione o azeite, a salsinha, o orégano e as azeitonas, misturando bem até formar uma pasta. Leve à geladeira por pelo menos 15 minutos para apurar o sabor antes de servir.',
  },
  {
    id: 'guacamole',
    titulo: 'Guacamole',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-75',
    ingredientes: ['1 avocado maduro', '1/2 tomate sem sementes picado', 'Suco de 1/2 limão', '1/4 de cebola roxa picada finamente', 'Sal e pimenta do reino a gosto'],
    modo_preparo: 'Em uma tigela, amasse a polpa do avocado com um garfo, deixando alguns pedaços. Adicione o tomate, a cebola e o suco de limão. Tempere com sal e pimenta e misture delicadamente. Sirva imediatamente.',
  },
  {
    id: 'ball-proteico',
    titulo: 'Ball Proteico',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-76',
    ingredientes: ['1/2 xícara de oleaginosas (amêndoas, castanhas)', '2 colheres de sopa de cacau em pó', '1 scoop de whey protein', '2 colheres de sopa de mel ou agave', 'Coco ralado para enrolar', '1/2 banana amassada', '2 colheres de sopa de aveia'],
    modo_preparo: 'Triture as oleaginosas em um processador. Em uma tigela, misture todos os ingredientes (exceto o coco ralado) até formar uma massa densa. Modele pequenas bolinhas com as mãos e passe no coco ralado. Leve à geladeira por 30 minutos para firmar.',
  },
  {
    id: 'granola-funcional',
    titulo: 'Granola Funcional',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-77',
    ingredientes: ['1 colher de sopa de óleo de coco', '1/2 xícara de amêndoas', '1/2 xícara de castanha de caju', '1/4 xícara de avelãs', '1/4 xícara de sementes de girassol', '1/4 xícara de coco ralado sem açúcar'],
    modo_preparo: 'Em uma frigideira grande, aqueça o óleo de coco em fogo baixo. Adicione as oleaginosas e as sementes, mexendo constantemente até dourarem levemente. Adicione o coco ralado no final e mexa por mais um minuto. Deixe esfriar completamente antes de guardar.',
  },
  {
    id: 'pao-de-aveia',
    titulo: 'Pão de Aveia',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-78',
    ingredientes: ['500g de farinha integral', '1 xícara de aveia em flocos', '10g de fermento biológico seco', '1 colher de sopa de açúcar mascavo', '1 ovo', '3 colheres de sopa de azeite', '1 colher de chá de sal', 'Aproximadamente 300ml de água morna'],
    modo_preparo: 'Em uma tigela, misture a farinha, a aveia, o fermento, o açúcar e o sal. Adicione o ovo, o azeite e a água aos poucos, sovando até obter uma massa macia e que não grude. Deixe a massa crescer por 1 hora. Modele o pão, coloque em uma forma e asse em forno a 180°C por 30-40 minutos.',
  },
  {
    id: 'pao-de-aveia-e-mel',
    titulo: 'Pão de Aveia e Mel',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-79',
    ingredientes: ['250ml de leite morno', '1 ovo', '2 colheres de sopa de azeite', '10g de fermento biológico seco', '2 colheres de sopa de açúcar mascavo', '1 colher de chá de sal', '2 xícaras de farinha de trigo integral', '1 xícara de flocos de aveia', '2 colheres de sopa de mel'],
    modo_preparo: 'No liquidificador, bata o leite, o ovo, o azeite e o fermento. Em uma tigela, misture os ingredientes secos. Despeje a mistura líquida, adicione o mel e sove. Coloque em uma forma de pão untada, deixe crescer por 40 minutos e asse em forno pré-aquecido a 180°C até dourar.',
  },
  {
    id: 'pao-de-banana',
    titulo: 'Pão de Banana',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-80',
    ingredientes: ['3 bananas maduras amassadas', '2 ovos', '1/4 xícara de óleo de coco', '1 e 1/2 xícara de aveia em flocos', '1 colher de chá de canela em pó', '1 colher de sopa de fermento em pó', '1 pitada de sal', '1/2 xícara de castanhas picadas (opcional)'],
    modo_preparo: 'Em uma tigela, misture as bananas amassadas com os ovos e o óleo de coco. Adicione a aveia, a canela, o sal e as castanhas, misturando bem. Incorpore o fermento por último. Despeje em uma forma de bolo inglês untada e asse em forno a 180°C por cerca de 40 minutos.',
  },
  {
    id: 'pao-de-maca-com-canela',
    titulo: 'Pão de Maçã com Canela Integral',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-81',
    ingredientes: ['1 maçã picada', '1/2 xícara de água', '2 colheres de açúcar mascavo', 'Canela a gosto', '2 xícaras de farinha integral', '1/2 xícara de farinha de aveia', '2 ovos', '1/4 xícara de óleo de coco', '1/2 xícara de iogurte natural', '1 colher de chá de goma xantana', '10g de fermento biológico seco'],
    modo_preparo: 'Cozinhe a maçã com a água, açúcar e canela até amolecer. Em uma tigela, misture as farinhas, a goma e o fermento. Adicione os ovos, óleo, iogurte e a mistura de maçã cozida. Sove, deixe crescer por 30 minutos e asse em forno a 180°C até dourar.',
  },
  {
    id: 'pao-integral-simples',
    titulo: 'Pão Integral',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-45',
    ingredientes: ['3 xícaras de farinha de trigo integral', '10g de fermento biológico seco', '1 e 1/2 xícara de água morna', '1 colher de chá de sal', '1 colher de sopa de açúcar mascavo', '2 colheres de sopa de óleo de coco', '2 colheres de sopa de linhaça'],
    modo_preparo: 'Em uma tigela, misture a farinha, o fermento, o sal e o açúcar. Adicione a água morna, o óleo e a linhaça, sovando bem por 10 minutos. Deixe a massa crescer em um local aquecido por 1 hora. Modele o pão e asse em forno pré-aquecido a 200°C por cerca de 30 minutos.',
  },
  {
    id: 'paozinho-de-aveia',
    titulo: 'Pãozinho de Aveia',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-82',
    ingredientes: ['1/2 pote de iogurte natural', '3 colheres de sopa de farelo de aveia', '1 clara de ovo', '1/2 colher de chá de fermento em pó', 'Temperos a gosto'],
    modo_preparo: 'Em uma tigela, misture bem todos os ingredientes. Despeje em um recipiente pequeno untado que possa ir ao micro-ondas e cozinhe em potência alta por 2 a 3 minutos, ou até firmar. Sirva puro ou com recheio.',
  },
  {
    id: 'paozinho-recheado-ovo',
    titulo: 'Pãozinho Recheado com Ovo',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-83',
    ingredientes: ['1/4 xícara de leite de coco', '1 colher de chá de vinagre', '3 colheres de sopa de farinha de aveia', '1/4 colher de chá de bicarbonato de sódio', '1/4 colher de chá de fermento em pó', 'Sal a gosto', '1 fio de azeite', '1 ovo'],
    modo_preparo: 'Misture o leite de coco com o vinagre e deixe descansar por 5 minutos. Adicione os ingredientes secos e o azeite, misturando bem. Em uma forminha de muffin untada, coloque metade da massa, quebre o ovo no centro, cubra com o restante da massa e asse em forno a 180°C até dourar.',
  },
  {
    id: 'paozinho-portugues',
    titulo: 'Pãozinho Português',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-84',
    ingredientes: ['1 pote de iogurte natural (170g)', '2 colheres de sopa de azeite', '1 colher de chá de fermento em pó', '1 pitada de sal', 'Aproximadamente 1 xícara de farinha de aveia', '1 gema para pincelar'],
    modo_preparo: 'Em uma tigela, misture o iogurte, o azeite, o sal e o fermento. Adicione a farinha de aveia aos poucos, até a massa ficar macia e desgrudar das mãos. Modele bolinhas, pincele com a gema e asse em forno pré-aquecido a 180°C por 20-25 minutos.',
  },
  {
    id: 'pao-tostado-abacate-ovo',
    titulo: 'Pão Tostado com Abacate e Ovo',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-85',
    ingredientes: ['2 ovos cozidos', '2 fatias de pão integral', '1/2 abacate maduro', '1 colher de chá de manteiga', 'Suco de limão a gosto', 'Sal e pimenta do reino a gosto'],
    modo_preparo: 'Toste as fatias de pão em uma frigideira com manteiga até dourarem. Em uma tigela, amasse o abacate com um garfo, tempere com limão, sal e pimenta. Espalhe a pasta de abacate sobre as torradas e finalize com os ovos cozidos fatiados por cima.',
  },
  {
    id: 'bolinho-de-banana',
    titulo: 'Bolinho de Banana',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-86',
    ingredientes: ['1 banana madura amassada', '1 ovo', '2 colheres de sopa de farinha de coco ou aveia', 'Canela em pó a gosto', '1/2 colher de chá de fermento em pó'],
    modo_preparo: 'Em uma caneca, misture bem todos os ingredientes com um garfo. Leve ao micro-ondas em potência alta por cerca de 2 a 3 minutos, até que o bolinho esteja firme. Espere amornar um pouco para consumir.',
  },
  {
    id: 'bolinho-de-cenoura',
    titulo: 'Bolinho de Cenoura',
    categoria: 'cafe-da-manha-da-nutri',
    imagem: 'breakfast-87',
    ingredientes: ['1/2 cenoura pequena cozida e amassada', '1 ovo', '3 colheres de sopa de farelo de aveia', '2 colheres de sopa de água', 'Adoçante a gosto', '1/2 colher de chá de fermento em pó'],
    modo_preparo: 'Bata todos os ingredientes no liquidificador ou mixer até obter uma massa homogênea. Despeje em uma caneca ou forminha de silicone e leve ao micro-ondas por cerca de 3 minutos em potência alta, ou até firmar.',
  },
  // Sobremesas Zero
  {
    id: 'mousse-de-maracuja-zero',
    titulo: 'Mousse de Maracujá Zero',
    categoria: 'sobremesas-zero',
    imagem: 'dessert-1',
    ingredientes: ['1 xícara de suco de maracujá concentrado sem açúcar', '1 lata de creme de leite light', '1/2 xícara de adoçante culinário (xilitol ou eritritol)', '1 envelope de gelatina incolor sem sabor'],
    modo_preparo: 'Hidrate a gelatina conforme as instruções da embalagem. No liquidificador, bata o suco de maracujá, o creme de leite e o adoçante. Adicione a gelatina hidratada e bata por mais um minuto. Despeje em taças individuais e leve para gelar por pelo menos 2 horas, ou até firmar completamente.',
  },
  // Bolos
  {
    id: 'bolo-de-cenoura-fit',
    titulo: 'Bolo de Cenoura Fit',
    categoria: 'bolos-para-comer-sem-culpa',
    imagem: 'cake-1',
    ingredientes: ['2 cenouras médias raladas', '3 ovos', '1/2 xícara de óleo de coco', '1 xícara de farinha de aveia', '1 xícara de adoçante culinário (xilitol)', '1 colher de sopa de fermento em pó'],
    modo_preparo: 'Pré-aqueça o forno a 180°C. No liquidificador, bata as cenouras, os ovos e o óleo de coco até obter uma mistura homogênea. Em uma tigela, misture a farinha de aveia e o adoçante. Despeje a mistura líquida sobre os secos e incorpore bem. Por último, adicione o fermento e mexa delicadamente. Asse em forma untada por cerca de 35 minutos.',
  },
  // Airfryer
  {
    id: 'frango-crocante-airfryer',
    titulo: 'Frango Crocante na Airfryer',
    categoria: 'airfryer-proteica',
    imagem: 'airfryer-1',
    ingredientes: ['500g de filé de frango em cubos ou tiras', 'Sal, pimenta do reino e páprica a gosto', '1/2 xícara de farinha de amêndoas ou farelo de aveia', '1 ovo batido'],
    modo_preparo: 'Tempere os pedaços de frango com sal, pimenta e páprica. Passe cada pedaço no ovo batido e em seguida na farinha de amêndoas, cobrindo bem. Disponha os pedaços na cesta da airfryer sem sobrepor. Programe por 20 minutos a 200°C, virando na metade do tempo para dourar por igual.',
  },
];
